name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Determine image tag
      id: tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "1.0.${{ github.run_number }}" > tag.txt
        elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
          echo "develop-${{ github.sha:0:6 }}" > tag.txt
        else
          echo "branch-${{ github.sha:0:6 }}" > tag.txt
        fi

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build -t ghcr.io/${{ github.repository }}/nugs-downloader:$((cat tag.txt)) -f Dockerfile .
        docker buildx build -t ghcr.io/${{ github.repository }}/nugs-downloader:latest -f Dockerfile .
        docker buildx rm --all --force
        docker push ghcr.io/${{ github.repository }}/nugs-downloader:$((cat tag.txt))
        docker push ghcr.io/${{ github.repository }}/nugs-downloader:latest
