name: Docker Build and Push

on:
  push:
    branches:
      - master
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags for master branch
        if: github.ref == 'refs/heads/master'
        run: |
          echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:1.0.${{ github.run_number }},ghcr.io/${{ github.repository }}:1.0" >> $GITHUB_ENV

      - name: Set tags for other branches
        if: github.ref != 'refs/heads/master'
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | tail -c 7)
          echo "DOCKER_TAGS=ghcr.io/${{ github.repository }}:branch-$SHORT_SHA" >> $GITHUB_ENV
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ env.DOCKER_TAGS }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache